DailyShop.UI/Controllers/HomeController.cs
using DailyShop.DA.SQL;
using DailyShop.Main.Contracts;
using DailyShop.Main.Models;
using DailyShop.Main.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyShop.UI.Controllers
{
    public class HomeController : Controller
    {
        IRepository<Product> context;
        IRepository<ProdCat> productCategories;
        private GroceryShopContext db = new GroceryShopContext();
        public HomeController(IRepository<Product> pContext, IRepository<ProdCat> pCatContext)
        {
            context = pContext;
            productCategories = pCatContext;
        }
        public ActionResult Index(string Category=null) /*Works even when no category is passed in which is why null is used*/
        {
            List<Product> products;
            List<ProdCat> categories = productCategories.Collection().ToList();
            if (Category == null)
            {
                products=context.Collection().ToList(); 
            }
            else 
            {
                products = context.Collection().Where(p => p.Cat == Category).ToList();
            }
            ProdListVM model = new ProdListVM();
            model.Products = products;
            model.ProductCategories = categories;


            return View(model);
        }
        public ActionResult Search(string searchBy, string search) 
        {
            if (searchBy == "Cat")
            {
                return View(db.Products.Where(x => x.Cat == search || search == null).ToList());
            }
            else 
            {
                return View(db.Products.Where(x => x.Name.StartsWith(search)||search==null).ToList());
            }
            

        }

        public ActionResult Details(string id) 
        {
            Product product = context.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            else 
            {
                return View(product);
            }
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DailyShop.UI/Controllers/TrollyController.cs
using DailyShop.Main.Contracts;
using DailyShop.Main.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DailyShop.UI.Controllers
{
    public class TrollyController : Controller
    {
        IRepository<Consumer> consumers;
        ITrollyServ trollyServ;
        ITOrderServ tOrderServ;
        public TrollyController(ITrollyServ TrollyServ, ITOrderServ TOrderServ, IRepository<Consumer> Consumers) 
        {
            this.trollyServ = TrollyServ;
            this.tOrderServ = TOrderServ;
            this.consumers = Consumers;
        }
        // GET: Trolly
        public ActionResult Index()
        {
            var model = trollyServ.GetTrollyItems(this.HttpContext);
            return View(model);
        }
        public ActionResult AddToTrolly(string Id) 
        {
            trollyServ.AddToTrolly(this.HttpContext, Id);
            return RedirectToAction("Index");
        }
        public ActionResult RemoveFromTrolly(string Id)
        {
            trollyServ.RemoveFromTrolly(this.HttpContext, Id);
            return RedirectToAction("Index");
        }
        public PartialViewResult TrollySummary() 
        {
            var trollySummary = trollyServ.GetTrollySum(this.HttpContext);

            return PartialView(trollySummary);
        }
        [Authorize]
        public ActionResult Checkout() 
        {
            Consumer consumer = consumers.Collection().FirstOrDefault(c => c.Email == User.Identity.Name);

            if (consumer != null)
            {
                TrollyOrder tOrder = new TrollyOrder()
                {
                    Email = consumer.Email,
                    City = consumer.City,
                    State = consumer.State,
                    FName = consumer.FName,
                    LName = consumer.LName
                };

                return View(tOrder);
            }
            else 
            {
                return RedirectToAction("Error");
            }
            
        }
        [HttpPost]
        [Authorize]
        public ActionResult Checkout(TrollyOrder trollyOrder) 
        {
            var trollyItems = trollyServ.GetTrollyItems(this.HttpContext);
            trollyOrder.TrollyOrderStatus = "Order successfully created";
            trollyOrder.Email = User.Identity.Name;

            //assuming Payment is processed
            trollyOrder.TrollyOrderStatus = "Payment authenticated Successfully";
            tOrderServ.CreateOrder(trollyOrder, trollyItems);
            trollyServ.CLearTrolly(this.HttpContext);


            return RedirectToAction("Thankyou", new { TrollyOrderId=trollyOrder.Id});
        }
        public ActionResult ThankYou(string TrollyOrderId) 
        {
            ViewBag.TrollyOrderId = TrollyOrderId;
            return View();
        }
    }
}

DailyShop.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DailyShop.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DailyShop.UI/Views/Home/Details.cshtml
@model DailyShop.Main.Models.Product

@{
    ViewBag.Title = Model.Name +" Details";
}
<h2>@Html.DisplayFor(model=>model.Name)</h2>
<div>
    <div class="col-md-2">
        <img class="img-responsive" src="~/Content/ProdImgUp/@Model.Img"/>
    </div>
    <div class="col-md-10">
        <dl class="dl-horizontal">




            <dt>
                @Html.DisplayNameFor(model => model.Desc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Desc)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                €@Html.DisplayFor(model => model.Price)
            </dd>
            <dt></dt>
            <dd><a href="@Url.Action("AddToTrolly", "Trolly", new { Id=Model.Id })" class="btn btn-default">Add to trolly</a></dd>
            <dt></dt>
            <dd>@Html.ActionLink("Back to List", "Index")</dd>
        </dl>
    </div>
</div>
 
<div class="cold-md-12 clearfix"></div>

DailyShop.UI/Views/Home/Index.cshtml
@model DailyShop.Main.ViewModels.ProdListVM
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="background-color:darkcyan;width: 1600px; height: 700px">
    <img class="img-responsive" style="width: 1600px; height: 500px" src="~/Content/ProdImgUp/GrocerBG.jpg" />
    <center><h1 style="color:aqua">The DailyGrocer</h1></center>
</div>


<center><h2>FRESH PRODUCTS</h2></center>
<div class="col-md-2">
    <h4>Categories include:</h4>
    <div class="list-group">
        @Html.ActionLink("ALL", "Index", null, new { @class = Request["Category"] == null ? "list-group-item active" : "list-group-item" })
        @foreach (var cat in Model.ProductCategories)
        {
            @Html.ActionLink(cat.CategoryName, "Index", new { Category = cat.CategoryName }, new { @class = Request["Category"] == cat.CategoryName ? "list-group-item active" : "list-group-item" })
        }
    </div>
</div>
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{
    <b> Search By:</b>
    @Html.RadioButton("searchBy", "Name", true)<text>Name</text>
    @Html.RadioButton("searchBy", "Cat")<text>Cat</text>
    <br />
    @Html.TextBox("search")
    <input type="submit" value="Search" />

}
<div class="col-md-10">
    @foreach (var item in Model.Products)
    {
        <div class="col-md-3" style="height:450px;border:solid thin whitesmoke">
            <div class="col-md-12">
                <img class="img" style="height:200px" src="~/Content/ProdImgUp/@item.Img" />
            </div>
            <div class="col-md-12">
                <h2><strong>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</strong></h2>
            </div>
            <div class="col-md-12">
                <h4>@item.Desc</h4>
            </div>
            <div class="col-md-12">
                <h4>₹@item.Price</h4>
            </div>
            <div class="col-md-12">
                <a href="@Url.Action("AddToTrolly", "Trolly", new { Id = item.Id })" class="btn btn-default">Add to trolly</a>
            </div>
        </div>
    }
</div>
<div class="col-md-12 clearfix" style="background-color:darkcyan" />